# Generated by Django 5.1.6 on 2025-04-04 13:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import plans.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Position"
                    ),
                ),
                (
                    "column_id",
                    models.CharField(
                        default="en-cours", max_length=50, verbose_name="Colonne"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("private", "Privé"),
                            ("company", "Entreprise"),
                            ("employee", "Salariés"),
                            ("visitor", "Visiteurs"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="Niveau d'accès",
                    ),
                ),
                (
                    "style",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Style de la note"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="forages", max_length=50, verbose_name="Catégorie"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="plans.plan",
                        verbose_name="Plan associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note géolocalisée",
                "verbose_name_plural": "Notes géolocalisées",
                "ordering": ["column_id", "order", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Texte du commentaire")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="plans.geonote",
                        verbose_name="Note associée",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire de note",
                "verbose_name_plural": "Commentaires de notes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=plans.models.note_photo_upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Taille de l'image en kilooctets",
                        verbose_name="Taille (KB)",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="plans.geonote",
                        verbose_name="Note associée",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo de note",
                "verbose_name_plural": "Photos de notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
