# Generated by Django 5.1.6 on 2025-04-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_alter_geonote_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geonote",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="plans.plan",
            ),
        ),
    ]
