# Generated by Django 5.1.6 on 2025-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_geonote_notecomment_notephoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                (
                    "color",
                    models.CharField(
                        default="#6B7280", max_length=20, verbose_name="Couleur"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Colonne par défaut"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Colonne de notes",
                "verbose_name_plural": "Colonnes de notes",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
