# Generated by Django 5.1.6 on 2025-04-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_notecolumn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geonote",
            options={
                "ordering": ["column", "order", "-updated_at"],
                "verbose_name": "Note géolocalisée",
                "verbose_name_plural": "Notes géolocalisées",
            },
        ),
        migrations.RemoveField(
            model_name="geonote",
            name="column_id",
        ),
        migrations.AddField(
            model_name="geonote",
            name="column",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="plans.notecolumn",
                verbose_name="Colonne",
            ),
        ),
    ]
