# Generated by Django 5.1.6 on 2025-04-07 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_geonote_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MapFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du filtre"),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Catégorie"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        limit_choices_to={"role": "ENTREPRISE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_filters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtre de carte",
                "verbose_name_plural": "Filtres de carte",
                "ordering": ["name"],
                "unique_together": {("name", "entreprise")},
            },
        ),
    ]
