# Generated by Django 5.1.6 on 2025-04-12 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_mapfilter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="geonote",
            name="enterprise_id",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "ENTREPRISE"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enterprise_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Entreprise associée",
            ),
        ),
    ]
