# Generated by Django 5.1.6 on 2025-05-03 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_geonote_enterprise_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="geonote",
            name="createur",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créateur",
            ),
            preserve_default=False,
        ),
    ]
