# Generated by Django 5.1.6 on 2025-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Identifiant unique du paramètre (ex: 'google_maps_api_key')",
                        max_length=100,
                        unique=True,
                        verbose_name="Clé du paramètre",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Valeur du paramètre (texte)",
                        null=True,
                        verbose_name="Valeur du paramètre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description de l'utilité du paramètre",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre d'application",
                "verbose_name_plural": "Paramètres d'application",
            },
        ),
    ]
