# Generated by Django 5.1.6 on 2025-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="ecowitt_api_key",
            field=models.CharField(
                blank=True,
                help_text="Clé API pour accéder aux services Ecowitt",
                max_length=100,
                null=True,
                verbose_name="Clé API Ecowitt",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="ecowitt_application_key",
            field=models.CharField(
                blank=True,
                help_text="Clé d'application pour accéder aux services Ecowitt",
                max_length=100,
                null=True,
                verbose_name="Clé d'application Ecowitt",
            ),
        ),
    ]
