# Generated by Django 5.1.6 on 2025-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="storage_quota",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Quota de stockage en mégaoctets pour les photos des notes",
                verbose_name="Quota de stockage (MB)",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="storage_used",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace de stockage actuellement utilisé en mégaoctets",
                verbose_name="Stockage utilisé (MB)",
            ),
        ),
    ]
